# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddToWallet.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pickle
import os
dir_path = os.path.dirname(os.path.realpath(__file__))
os.chdir(dir_path)


class Ui_AddToWallet(object):
    def setupUi(self, AddToWallet):

        self.page = AddToWallet
        AddToWallet.setObjectName("AddToWallet")
        AddToWallet.resize(400, 300)
        AddToWallet.setMinimumSize(QtCore.QSize(400, 300))
        AddToWallet.setMaximumSize(QtCore.QSize(400, 300))
        AddToWallet.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AddToWallet)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LB = QtWidgets.QLabel(AddToWallet)
        self.LB.setMaximumSize(QtCore.QSize(500, 50))
        self.LB.setObjectName("LB")
        self.verticalLayout_2.addWidget(self.LB)
        self.Money_LE = QtWidgets.QLineEdit(AddToWallet)
        self.Money_LE.setMinimumSize(QtCore.QSize(200, 100))
        self.Money_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Money_LE.setObjectName("Money_LE")
        self.verticalLayout_2.addWidget(self.Money_LE)
        self.Money_PB = QtWidgets.QPushButton(AddToWallet)
        self.Money_PB.setMinimumSize(QtCore.QSize(200, 0))
        self.Money_PB.setMaximumSize(QtCore.QSize(300, 60))
        self.Money_PB.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Money_PB.setObjectName("Money_PB")
        self.verticalLayout_2.addWidget(self.Money_PB, 0, QtCore.Qt.AlignHCenter)

        self.Money_PB.clicked.connect(self.pushbutt)

        self.retranslateUi(AddToWallet)
        QtCore.QMetaObject.connectSlotsByName(AddToWallet)

    def retranslateUi(self, AddToWallet):
        _translate = QtCore.QCoreApplication.translate
        AddToWallet.setWindowTitle(_translate("AddToWallet", "Form"))
        self.LB.setText(_translate("AddToWallet", "<html><head/><body><p align=\"right\"><span style=\" font-size:16pt; font-weight:600;\">افزودن موجودی</span></p></body></html>"))
        self.Money_LE.setPlaceholderText(_translate("AddToWallet", "مقدار پول را وارد کنید."))
        self.Money_PB.setText(_translate("AddToWallet", "افزایش"))


    def pushbutt(self):
        money = int(self.Money_LE.text())
        if money > 0:

            with open('../DataBase/Logined.pkl', 'rb') as handle:
                c = pickle.load(handle)
            c.Wallet += money
            with open('../DataBase/Logined.pkl', 'wb') as handle:
                pickle.dump(c, handle)
            
            self.cart()

    def cart(self):
        from Customer_Cart import Ui_Main_Customer
        self.CartPage = QtWidgets.QWidget()
        self.ui = Ui_Main_Customer()
        self.ui.setupUi(self.CartPage)
        
        self.page.hide()
        self.CartPage.show()
