# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Customer_Cart.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main_Customer(object):
    def setupUi(self, Main_Customer):
        Main_Customer.setObjectName("Main_Customer")
        Main_Customer.resize(1038, 570)
        Main_Customer.setMinimumSize(QtCore.QSize(1038, 570))
        Main_Customer.setMaximumSize(QtCore.QSize(1038, 570))
        self.verticalLayout = QtWidgets.QVBoxLayout(Main_Customer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Header = QtWidgets.QHBoxLayout()
        self.Header.setObjectName("Header")
        self.pushButton_2 = QtWidgets.QPushButton(Main_Customer)
        self.pushButton_2.setMinimumSize(QtCore.QSize(73, 69))
        self.pushButton_2.setMaximumSize(QtCore.QSize(73, 69))
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Images/Back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_2.setObjectName("pushButton_2")
        self.Header.addWidget(self.pushButton_2)
        self.Exit_PB = QtWidgets.QPushButton(Main_Customer)
        self.Exit_PB.setMinimumSize(QtCore.QSize(73, 69))
        self.Exit_PB.setMaximumSize(QtCore.QSize(73, 69))
        self.Exit_PB.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Images/Exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Exit_PB.setIcon(icon1)
        self.Exit_PB.setIconSize(QtCore.QSize(60, 60))
        self.Exit_PB.setAutoDefault(False)
        self.Exit_PB.setDefault(False)
        self.Exit_PB.setFlat(False)
        self.Exit_PB.setObjectName("Exit_PB")
        self.Header.addWidget(self.Exit_PB)
        self.Cart_PB = QtWidgets.QPushButton(Main_Customer)
        self.Cart_PB.setMinimumSize(QtCore.QSize(73, 69))
        self.Cart_PB.setMaximumSize(QtCore.QSize(150, 69))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Cart_PB.setFont(font)
        self.Cart_PB.setStyleSheet("color: #f08804;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Images/Cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Cart_PB.setIcon(icon2)
        self.Cart_PB.setIconSize(QtCore.QSize(60, 60))
        self.Cart_PB.setObjectName("Cart_PB")
        self.Header.addWidget(self.Cart_PB)
        self.Wishlist_PB = QtWidgets.QPushButton(Main_Customer)
        self.Wishlist_PB.setMinimumSize(QtCore.QSize(73, 69))
        self.Wishlist_PB.setMaximumSize(QtCore.QSize(73, 69))
        self.Wishlist_PB.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Images/WishList.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Wishlist_PB.setIcon(icon3)
        self.Wishlist_PB.setIconSize(QtCore.QSize(60, 60))
        self.Wishlist_PB.setObjectName("Wishlist_PB")
        self.Header.addWidget(self.Wishlist_PB)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Header.addItem(spacerItem)
        self.Specs_GL = QtWidgets.QGridLayout()
        self.Specs_GL.setObjectName("Specs_GL")
        self.Email_var = QtWidgets.QLabel(Main_Customer)
        self.Email_var.setObjectName("Email_var")
        self.Specs_GL.addWidget(self.Email_var, 1, 1, 1, 1)
        self.Email_LB = QtWidgets.QLabel(Main_Customer)
        self.Email_LB.setObjectName("Email_LB")
        self.Specs_GL.addWidget(self.Email_LB, 1, 2, 1, 1)
        self.ID_LB = QtWidgets.QLabel(Main_Customer)
        self.ID_LB.setObjectName("ID_LB")
        self.Specs_GL.addWidget(self.ID_LB, 2, 2, 1, 1)
        self.ID_var = QtWidgets.QLabel(Main_Customer)
        self.ID_var.setObjectName("ID_var")
        self.Specs_GL.addWidget(self.ID_var, 2, 1, 1, 1)
        self.Name_var = QtWidgets.QLabel(Main_Customer)
        self.Name_var.setObjectName("Name_var")
        self.Specs_GL.addWidget(self.Name_var, 0, 1, 1, 1)
        self.Name_LB = QtWidgets.QLabel(Main_Customer)
        self.Name_LB.setObjectName("Name_LB")
        self.Specs_GL.addWidget(self.Name_LB, 0, 2, 1, 1)
        self.Header.addLayout(self.Specs_GL)
        self.Header_HL = QtWidgets.QHBoxLayout()
        self.Header_HL.setObjectName("Header_HL")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Header_HL.addItem(spacerItem1)
        self.Unit_LB = QtWidgets.QLabel(Main_Customer)
        self.Unit_LB.setMaximumSize(QtCore.QSize(500, 50))
        self.Unit_LB.setObjectName("Unit_LB")
        self.Header_HL.addWidget(self.Unit_LB, 0, QtCore.Qt.AlignRight)
        self.Money_var = QtWidgets.QLabel(Main_Customer)
        self.Money_var.setMaximumSize(QtCore.QSize(500, 50))
        self.Money_var.setObjectName("Money_var")
        self.Header_HL.addWidget(self.Money_var, 0, QtCore.Qt.AlignLeft)
        self.Bal_LB = QtWidgets.QLabel(Main_Customer)
        self.Bal_LB.setMaximumSize(QtCore.QSize(500, 50))
        self.Bal_LB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Bal_LB.setObjectName("Bal_LB")
        self.Header_HL.addWidget(self.Bal_LB, 0, QtCore.Qt.AlignRight)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Header_HL.addItem(spacerItem2)
        self.Shop_Name_LB = QtWidgets.QLabel(Main_Customer)
        self.Shop_Name_LB.setMaximumSize(QtCore.QSize(500, 50))
        self.Shop_Name_LB.setObjectName("Shop_Name_LB")
        self.Header_HL.addWidget(self.Shop_Name_LB)
        self.Header_HL.setStretch(0, 4)
        self.Header_HL.setStretch(4, 4)
        self.Header.addLayout(self.Header_HL)
        self.Header.setStretch(6, 1)
        self.verticalLayout.addLayout(self.Header)
        self.line = QtWidgets.QFrame(Main_Customer)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.Main = QtWidgets.QGridLayout()
        self.Main.setObjectName("Main")
        self.Main_VL = QtWidgets.QVBoxLayout()
        self.Main_VL.setObjectName("Main_VL")
        self.Main_SA = QtWidgets.QScrollArea(Main_Customer)
        self.Main_SA.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Main_SA.setWidgetResizable(True)
        self.Main_SA.setObjectName("Main_SA")
        self.Main_QW = QtWidgets.QWidget()
        self.Main_QW.setGeometry(QtCore.QRect(0, -517, 989, 971))
        self.Main_QW.setObjectName("Main_QW")
        self.gridLayout = QtWidgets.QGridLayout(self.Main_QW)
        self.gridLayout.setObjectName("gridLayout")
        self.Item_GL_1 = QtWidgets.QWidget(self.Main_QW)
        self.Item_GL_1.setMinimumSize(QtCore.QSize(900, 370))
        self.Item_GL_1.setMaximumSize(QtCore.QSize(1000, 350))
        self.Item_GL_1.setStyleSheet("background-color:White;")
        self.Item_GL_1.setObjectName("Item_GL_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Item_GL_1)
        self.gridLayout_2.setContentsMargins(30, 30, 30, 30)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Description = QtWidgets.QWidget(self.Item_GL_1)
        self.Description.setStyleSheet("background-color: rgb(243, 243, 243);\n"
"")
        self.Description.setObjectName("Description")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Description)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Name = QtWidgets.QToolButton(self.Description)
        self.Name.setMinimumSize(QtCore.QSize(719, 0))
        self.Name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Name.setStyleSheet("background-color:rgb(0,0,0,0);")
        self.Name.setObjectName("Name")
        self.verticalLayout_2.addWidget(self.Name, 0, QtCore.Qt.AlignHCenter)
        self.Rate = QtWidgets.QToolButton(self.Description)
        self.Rate.setMinimumSize(QtCore.QSize(90, 0))
        self.Rate.setStyleSheet("background-color: rgb(0,0,0,0)")
        self.Rate.setIcon(icon3)
        self.Rate.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Rate.setObjectName("Rate")
        self.verticalLayout_2.addWidget(self.Rate, 0, QtCore.Qt.AlignHCenter)
        self.Amount = QtWidgets.QLabel(self.Description)
        self.Amount.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Amount.setObjectName("Amount")
        self.verticalLayout_2.addWidget(self.Amount, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addWidget(self.Description, 3, 1, 1, 1)
        self.Picture_1 = QtWidgets.QToolButton(self.Item_GL_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Picture_1.sizePolicy().hasHeightForWidth())
        self.Picture_1.setSizePolicy(sizePolicy)
        self.Picture_1.setMinimumSize(QtCore.QSize(800, 150))
        self.Picture_1.setMaximumSize(QtCore.QSize(1000, 150))
        self.Picture_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Picture_1.setAutoFillBackground(False)
        self.Picture_1.setStyleSheet("background-color:rgb(0,0,0,0);")
        self.Picture_1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Images/UserUploaded imgs/Product.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Picture_1.setIcon(icon4)
        self.Picture_1.setIconSize(QtCore.QSize(200, 200))
        self.Picture_1.setObjectName("Picture_1")
        self.gridLayout_2.addWidget(self.Picture_1, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.toolButton = QtWidgets.QToolButton(self.Item_GL_1)
        self.toolButton.setMinimumSize(QtCore.QSize(100, 150))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../Images/Remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon5)
        self.toolButton.setIconSize(QtCore.QSize(60, 60))
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton.setObjectName("toolButton")
        self.verticalLayout_3.addWidget(self.toolButton)
        self.spinBox = QtWidgets.QSpinBox(self.Item_GL_1)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_3.addWidget(self.spinBox)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.Item_GL_1, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.Main_QW)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.Top_Line = QtWidgets.QFrame(self.Main_QW)
        self.Top_Line.setFrameShape(QtWidgets.QFrame.HLine)
        self.Top_Line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Top_Line.setObjectName("Top_Line")
        self.gridLayout.addWidget(self.Top_Line, 1, 0, 1, 1)
        self.Bottom_Line = QtWidgets.QFrame(self.Main_QW)
        self.Bottom_Line.setFrameShape(QtWidgets.QFrame.HLine)
        self.Bottom_Line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Bottom_Line.setObjectName("Bottom_Line")
        self.gridLayout.addWidget(self.Bottom_Line, 5, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 4, 0, 1, 1)
        self.gridWidget = QtWidgets.QWidget(self.Main_QW)
        self.gridWidget.setStyleSheet("")
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 0, 0, 1, 1)
        self.toolButton1 = QtWidgets.QToolButton(self.gridWidget)
        self.toolButton1.setMinimumSize(QtCore.QSize(100, 100))
        self.toolButton1.setIcon(icon2)
        self.toolButton1.setIconSize(QtCore.QSize(60, 60))
        self.toolButton1.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton1.setObjectName("toolButton1")
        self.gridLayout_4.addWidget(self.toolButton1, 0, 2, 1, 1, QtCore.Qt.AlignRight)
        self.label_2 = QtWidgets.QLabel(self.gridWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 2, 1, 1)
        self.toolButton2 = QtWidgets.QToolButton(self.gridWidget)
        self.toolButton2.setMinimumSize(QtCore.QSize(160, 100))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../Images/Money.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton2.setIcon(icon6)
        self.toolButton2.setIconSize(QtCore.QSize(60, 60))
        self.toolButton2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton2.setObjectName("toolButton2")
        self.gridLayout_4.addWidget(self.toolButton2, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.gridWidget, 6, 0, 1, 1)
        self.Item_GL_3 = QtWidgets.QWidget(self.Main_QW)
        self.Item_GL_3.setMinimumSize(QtCore.QSize(900, 370))
        self.Item_GL_3.setMaximumSize(QtCore.QSize(1000, 350))
        self.Item_GL_3.setStyleSheet("background-color:White;")
        self.Item_GL_3.setObjectName("Item_GL_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Item_GL_3)
        self.gridLayout_3.setContentsMargins(30, 30, 30, 30)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Description_2 = QtWidgets.QWidget(self.Item_GL_3)
        self.Description_2.setStyleSheet("background-color: rgb(243, 243, 243);\n"
"")
        self.Description_2.setObjectName("Description_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Description_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Name_2 = QtWidgets.QToolButton(self.Description_2)
        self.Name_2.setMinimumSize(QtCore.QSize(719, 0))
        self.Name_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Name_2.setStyleSheet("background-color:rgb(0,0,0,0);")
        self.Name_2.setObjectName("Name_2")
        self.verticalLayout_5.addWidget(self.Name_2, 0, QtCore.Qt.AlignHCenter)
        self.Rate_2 = QtWidgets.QToolButton(self.Description_2)
        self.Rate_2.setMinimumSize(QtCore.QSize(90, 0))
        self.Rate_2.setStyleSheet("background-color: rgb(0,0,0,0)")
        self.Rate_2.setIcon(icon3)
        self.Rate_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Rate_2.setObjectName("Rate_2")
        self.verticalLayout_5.addWidget(self.Rate_2, 0, QtCore.Qt.AlignHCenter)
        self.Amount_2 = QtWidgets.QLabel(self.Description_2)
        self.Amount_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Amount_2.setObjectName("Amount_2")
        self.verticalLayout_5.addWidget(self.Amount_2, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_3.addWidget(self.Description_2, 3, 1, 1, 1)
        self.Picture_2 = QtWidgets.QToolButton(self.Item_GL_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Picture_2.sizePolicy().hasHeightForWidth())
        self.Picture_2.setSizePolicy(sizePolicy)
        self.Picture_2.setMinimumSize(QtCore.QSize(800, 150))
        self.Picture_2.setMaximumSize(QtCore.QSize(1000, 150))
        self.Picture_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Picture_2.setAutoFillBackground(False)
        self.Picture_2.setStyleSheet("background-color:rgb(0,0,0,0);")
        self.Picture_2.setText("")
        self.Picture_2.setIcon(icon4)
        self.Picture_2.setIconSize(QtCore.QSize(200, 200))
        self.Picture_2.setObjectName("Picture_2")
        self.gridLayout_3.addWidget(self.Picture_2, 0, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.toolButton_4 = QtWidgets.QToolButton(self.Item_GL_3)
        self.toolButton_4.setMinimumSize(QtCore.QSize(100, 150))
        self.toolButton_4.setIcon(icon5)
        self.toolButton_4.setIconSize(QtCore.QSize(60, 60))
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_4.setObjectName("toolButton_4")
        self.verticalLayout_6.addWidget(self.toolButton_4)
        self.spinBox_3 = QtWidgets.QSpinBox(self.Item_GL_3)
        self.spinBox_3.setObjectName("spinBox_3")
        self.verticalLayout_6.addWidget(self.spinBox_3)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.Item_GL_3, 3, 0, 1, 1)
        self.Main_SA.setWidget(self.Main_QW)
        self.Main_VL.addWidget(self.Main_SA)
        self.Main.addLayout(self.Main_VL, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.Main)

        self.retranslateUi(Main_Customer)
        QtCore.QMetaObject.connectSlotsByName(Main_Customer)

    def retranslateUi(self, Main_Customer):
        _translate = QtCore.QCoreApplication.translate
        Main_Customer.setWindowTitle(_translate("Main_Customer", "Form"))
        self.Cart_PB.setText(_translate("Main_Customer", "Count"))
        self.Email_var.setText(_translate("Main_Customer", "Email"))
        self.Email_LB.setText(_translate("Main_Customer", "ایمیل :"))
        self.ID_LB.setText(_translate("Main_Customer", "آیدی :"))
        self.ID_var.setText(_translate("Main_Customer", "ID"))
        self.Name_var.setText(_translate("Main_Customer", "Name"))
        self.Name_LB.setText(_translate("Main_Customer", "نام : "))
        self.Unit_LB.setText(_translate("Main_Customer", "ریال"))
        self.Money_var.setText(_translate("Main_Customer", "<html><head/><body><p><span style=\" font-size:10pt;\">Money</span></p></body></html>"))
        self.Bal_LB.setText(_translate("Main_Customer", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">: موجودی</span></p></body></html>"))
        self.Shop_Name_LB.setText(_translate("Main_Customer", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">فروشگاه من</span></p></body></html>"))
        self.Name.setText(_translate("Main_Customer", "Name"))
        self.Rate.setText(_translate("Main_Customer", "Rate / 5"))
        self.Amount.setText(_translate("Main_Customer", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">ریال</span><span style=\" font-size:12pt; font-weight:600;\"> Amount</span></p></body></html>"))
        self.toolButton.setText(_translate("Main_Customer", "حذف"))
        self.label.setText(_translate("Main_Customer", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">لیست خرید</span></p></body></html>"))
        self.toolButton1.setText(_translate("Main_Customer", "خرید"))
        self.label_2.setText(_translate("Main_Customer", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600; color:#ff0000;\">! موجودی شما کافی نمیباشد</span></p></body></html>"))
        self.toolButton2.setText(_translate("Main_Customer", "افزودن موجودی"))
        self.Name_2.setText(_translate("Main_Customer", "Name"))
        self.Rate_2.setText(_translate("Main_Customer", "Rate / 5"))
        self.Amount_2.setText(_translate("Main_Customer", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">ریال</span><span style=\" font-size:12pt; font-weight:600;\"> Amount</span></p></body></html>"))
        self.toolButton_4.setText(_translate("Main_Customer", "حذف"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main_Customer = QtWidgets.QWidget()
    ui = Ui_Main_Customer()
    ui.setupUi(Main_Customer)
    Main_Customer.show()
    sys.exit(app.exec_())

