# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Customer_Cart.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
import pickle
import os

dir_path = os.path.dirname(os.path.realpath(__file__))
os.chdir(dir_path)

class Ui_Main_Customer(object):
    def setupUi(self, Main_Customer):
        self.spinbox_list = []
        self.page = Main_Customer
        Main_Customer.setObjectName("Main_Customer")
        Main_Customer.resize(1038, 570)
        Main_Customer.setMinimumSize(QtCore.QSize(1038, 570))
        Main_Customer.setMaximumSize(QtCore.QSize(1038, 570))
        self.verticalLayout = QtWidgets.QVBoxLayout(Main_Customer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Header = QtWidgets.QHBoxLayout()
        self.Header.setObjectName("Header")
        self.pushButton_2 = QtWidgets.QPushButton(Main_Customer)
        self.pushButton_2.setMinimumSize(QtCore.QSize(73, 69))
        self.pushButton_2.setMaximumSize(QtCore.QSize(73, 69))
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Images/Back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_2.setObjectName("pushButton_2")
        self.Header.addWidget(self.pushButton_2)
        self.Exit_PB = QtWidgets.QPushButton(Main_Customer)
        self.Exit_PB.setMinimumSize(QtCore.QSize(73, 69))
        self.Exit_PB.setMaximumSize(QtCore.QSize(73, 69))
        self.Exit_PB.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Images/Exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Exit_PB.setIcon(icon1)
        self.Exit_PB.setIconSize(QtCore.QSize(60, 60))
        self.Exit_PB.setAutoDefault(False)
        self.Exit_PB.setDefault(False)
        self.Exit_PB.setFlat(False)
        self.Exit_PB.setObjectName("Exit_PB")
        self.Header.addWidget(self.Exit_PB)
        self.Cart_PB = QtWidgets.QPushButton(Main_Customer)
        self.Cart_PB.setMinimumSize(QtCore.QSize(73, 69))
        self.Cart_PB.setMaximumSize(QtCore.QSize(150, 69))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Cart_PB.setFont(font)
        self.Cart_PB.setStyleSheet("color: #f08804;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Images/Cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Cart_PB.setIcon(icon2)
        self.Cart_PB.setIconSize(QtCore.QSize(60, 60))
        self.Cart_PB.setObjectName("Cart_PB")
        self.Header.addWidget(self.Cart_PB)
        self.Wishlist_PB = QtWidgets.QPushButton(Main_Customer)
        self.Wishlist_PB.setMinimumSize(QtCore.QSize(73, 69))
        self.Wishlist_PB.setMaximumSize(QtCore.QSize(73, 69))
        self.Wishlist_PB.setText("")
        self.icon3 = QtGui.QIcon()
        self.icon3.addPixmap(QtGui.QPixmap("../Images/WishList.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Wishlist_PB.setIcon(self.icon3)
        self.Wishlist_PB.setIconSize(QtCore.QSize(60, 60))
        self.Wishlist_PB.setObjectName("Wishlist_PB")
        self.Header.addWidget(self.Wishlist_PB)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Header.addItem(spacerItem)
        self.Specs_GL = QtWidgets.QGridLayout()
        self.Specs_GL.setObjectName("Specs_GL")
        self.Email_var = QtWidgets.QLabel(Main_Customer)
        self.Email_var.setObjectName("Email_var")
        self.Specs_GL.addWidget(self.Email_var, 1, 1, 1, 1)
        self.Email_LB = QtWidgets.QLabel(Main_Customer)
        self.Email_LB.setObjectName("Email_LB")
        self.Specs_GL.addWidget(self.Email_LB, 1, 2, 1, 1)
        self.ID_LB = QtWidgets.QLabel(Main_Customer)
        self.ID_LB.setObjectName("ID_LB")
        self.Specs_GL.addWidget(self.ID_LB, 2, 2, 1, 1)
        self.ID_var = QtWidgets.QLabel(Main_Customer)
        self.ID_var.setObjectName("ID_var")
        self.Specs_GL.addWidget(self.ID_var, 2, 1, 1, 1)
        self.Name_var = QtWidgets.QLabel(Main_Customer)
        self.Name_var.setObjectName("Name_var")
        self.Specs_GL.addWidget(self.Name_var, 0, 1, 1, 1)
        self.Name_LB = QtWidgets.QLabel(Main_Customer)
        self.Name_LB.setObjectName("Name_LB")
        self.Specs_GL.addWidget(self.Name_LB, 0, 2, 1, 1)
        self.Header.addLayout(self.Specs_GL)
        self.Header_HL = QtWidgets.QHBoxLayout()
        self.Header_HL.setObjectName("Header_HL")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Header_HL.addItem(spacerItem1)
        self.Unit_LB = QtWidgets.QLabel(Main_Customer)
        self.Unit_LB.setMaximumSize(QtCore.QSize(500, 50))
        self.Unit_LB.setObjectName("Unit_LB")
        self.Header_HL.addWidget(self.Unit_LB, 0, QtCore.Qt.AlignRight)
        self.Money_var = QtWidgets.QLabel(Main_Customer)
        self.Money_var.setMaximumSize(QtCore.QSize(500, 50))
        self.Money_var.setObjectName("Money_var")
        self.Header_HL.addWidget(self.Money_var, 0, QtCore.Qt.AlignLeft)
        self.Bal_LB = QtWidgets.QLabel(Main_Customer)
        self.Bal_LB.setMaximumSize(QtCore.QSize(500, 50))
        self.Bal_LB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Bal_LB.setObjectName("Bal_LB")
        self.Header_HL.addWidget(self.Bal_LB, 0, QtCore.Qt.AlignRight)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Header_HL.addItem(spacerItem2)
        self.Shop_Name_LB = QtWidgets.QLabel(Main_Customer)
        self.Shop_Name_LB.setMaximumSize(QtCore.QSize(500, 50))
        self.Shop_Name_LB.setObjectName("Shop_Name_LB")
        self.Header_HL.addWidget(self.Shop_Name_LB)
        self.Header_HL.setStretch(0, 4)
        self.Header_HL.setStretch(4, 4)
        self.Header.addLayout(self.Header_HL)
        self.Header.setStretch(6, 1)
        self.verticalLayout.addLayout(self.Header)
        self.line = QtWidgets.QFrame(Main_Customer)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.Main = QtWidgets.QGridLayout()
        self.Main.setObjectName("Main")
        self.Main_VL = QtWidgets.QVBoxLayout()
        self.Main_VL.setObjectName("Main_VL")
        self.Main_SA = QtWidgets.QScrollArea(Main_Customer)
        self.Main_SA.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Main_SA.setWidgetResizable(True)
        self.Main_SA.setObjectName("Main_SA")
        self.Main_QW = QtWidgets.QWidget()
        self.Main_QW.setGeometry(QtCore.QRect(0, 0, 989, 974))
        self.Main_QW.setObjectName("Main_QW")
        



        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Main_QW)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.Main_QW)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label, 0, QtCore.Qt.AlignRight)
        self.Top_Line = QtWidgets.QFrame(self.Main_QW)
        self.Top_Line.setFrameShape(QtWidgets.QFrame.HLine)
        self.Top_Line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Top_Line.setObjectName("Top_Line")
        self.verticalLayout_4.addWidget(self.Top_Line)
        self.btn_grp = QtWidgets.QButtonGroup()
        self.btn_grp.setExclusive(True)
        with open('../DataBase/logined.pkl', 'rb') as handle:
            self.c = pickle.load(handle)
        self.Add_Product()
        self.btn_grp.buttonClicked.connect(self.confirmbutton)




        self.gridWidget = QtWidgets.QWidget(self.Main_QW)
        self.gridWidget.setStyleSheet("")
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 0, 1, 1)
        self.toolButton1 = QtWidgets.QToolButton(self.gridWidget)
        self.toolButton1.setMinimumSize(QtCore.QSize(100, 100))
        self.toolButton1.setIcon(icon2)
        self.toolButton1.setIconSize(QtCore.QSize(60, 60))
        self.toolButton1.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton1.setObjectName("toolButton1")
        self.gridLayout_4.addWidget(self.toolButton1, 0, 2, 1, 1, QtCore.Qt.AlignRight)
        self.label_2 = QtWidgets.QLabel(self.gridWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 2, 1, 1)
        self.toolButton2 = QtWidgets.QToolButton(self.gridWidget)
        self.toolButton2.setMinimumSize(QtCore.QSize(160, 100))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../Images/Money.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton2.setIcon(icon6)
        self.toolButton2.setIconSize(QtCore.QSize(60, 60))
        self.toolButton2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton2.setObjectName("toolButton2")
        self.gridLayout_4.addWidget(self.toolButton2, 0, 3, 1, 1)
        
        self.verticalLayout_4.addWidget(self.gridWidget)
        self.Bottom_Line = QtWidgets.QFrame(self.Main_QW)
        self.Bottom_Line.setGeometry(QtCore.QRect(11, 818, 967, 16))
        self.Bottom_Line.setFrameShape(QtWidgets.QFrame.HLine)
        self.Bottom_Line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Bottom_Line.setObjectName("Bottom_Line")
        self.Main_SA.setWidget(self.Main_QW)
        self.Main_VL.addWidget(self.Main_SA)
        self.Main.addLayout(self.Main_VL, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.Main)




        ### Header ###
       
        self.pushButton_2.clicked.connect(self.back)  #pushButton_2 = Back_PB
        self.Exit_PB.clicked.connect(self.logout)
        self.Wishlist_PB.clicked.connect(self.wishlist)
        self.Cart_PB.clicked.connect(self.cart)
        self.Email_var.setText(self.c.Email)
        self.ID_var.setText(self.c.ID)
        self.Name_var.setText(self.c.Name)
        self.Money_var.setText(str(self.c.Wallet))
        self.Cart_PB.setText(str(self.sumofcart()))
        ### Main ###
        self.toolButton1.clicked.connect(self.buy)
        self.toolButton2.clicked.connect(self.payment)



        self.retranslateUi(Main_Customer)
        QtCore.QMetaObject.connectSlotsByName(Main_Customer)

    def retranslateUi(self, Main_Customer):
        _translate = QtCore.QCoreApplication.translate
        Main_Customer.setWindowTitle(_translate("Main_Customer", "Cart"))
        self.Email_LB.setText(_translate("Main_Customer", "ایمیل :"))
        self.ID_LB.setText(_translate("Main_Customer", "آیدی :"))
        self.Name_LB.setText(_translate("Main_Customer", "نام : "))
        self.Unit_LB.setText(_translate("Main_Customer", "ریال"))
        self.Bal_LB.setText(_translate("Main_Customer", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">: موجودی</span></p></body></html>"))
        self.Shop_Name_LB.setText(_translate("Main_Customer", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">فروشگاه من</span></p></body></html>"))
        self.label.setText(_translate("Main_Customer", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">لیست خرید</span></p></body></html>"))
        self.label_2.setText(_translate("Main_Customer", f"<html><head/><body><p align=\"right\"><span style=\" font-weight:600; color:black;\">مجموع کل :{self.sumofcost()} ریال</span></p></body></html>"))
        self.toolButton1.setText(_translate("Main_Customer", "خرید"))
        self.toolButton2.setText(_translate("Main_Customer", "افزودن موجودی"))

    
### Header ###
    def logout(self):
        with open('../DataBase/logined.pkl', 'wb') as handle:
            pickle.dump(0, handle)
        self.page.close()
        os.system('python Main.py')

    def wishlist(self):
        from Customer_WishList import Ui_Main_Customer
        self.WishListPage = QtWidgets.QWidget()
        self.ui = Ui_Main_Customer()
        self.ui.setupUi(self.WishListPage)
        
        self.page.hide()
        self.WishListPage.show()

    def cart(self):
        from Customer_Cart import Ui_Main_Customer
        self.CartPage = QtWidgets.QWidget()
        self.ui = Ui_Main_Customer()
        self.ui.setupUi(self.CartPage)
        
        self.page.hide()
        self.CartPage.show()
    
    def back(self):
        from Customer_Main import Ui_Main_Customer
        self.MainPage = QtWidgets.QWidget()
        self.ui = Ui_Main_Customer()
        self.ui.setupUi(self.MainPage)
        
        self.page.hide()
        self.MainPage.show()
    ### Main ###
    def buy(self):
        from BuyList import BuyList
        BL = BuyList()
        sum = self.sumofcost()
        if int(sum) <= int(self.c.Wallet):
            with open('../DataBase/ListOfBuys.pkl', 'rb') as handle:
                listofbuys = pickle.load(handle)
            for cc in self.c.Cart:
                BL.AddBuy(cc)
            listofbuys.append(BL)
            with open('../DataBase/ListOfBuys.pkl', 'wb') as handle:
                pickle.dump(listofbuys, handle)
    
            self.c.Cart = []
            self.c.Wallet -= int(sum)

            with open('../DataBase/Customers.pkl', 'rb') as handle:
                Customers_List = pickle.load(handle)
            for i,C in enumerate(Customers_List):
                if self.c.Email == C.Email:
                    Customers_List[i] = self.c
            with open('../DataBase/Customers.pkl', 'wb') as handle:
                pickle.dump(Customers_List, handle)
            with open('../DataBase/logined.pkl', 'wb') as handle:
                pickle.dump(self.c, handle)

            self.refresh()
        else:
            self.label_2.setText( f"<html><head/><body><p align=\"right\"><span style=\" font-weight:600; color:red;\">مجموع کل :{self.sumofcost()} ریال ... موجودی شما کافی نمیباشد</span></p></body></html>")

    def payment(self):
        from AddToWallet import Ui_AddToWallet
        self.Page = QtWidgets.QWidget()
        self.ui = Ui_AddToWallet()
        self.ui.setupUi(self.Page)
        
        self.page.hide()
        self.Page.show()


    def Add_Product(self):
        Cart_List = self.c.Cart
        _translate = QtCore.QCoreApplication.translate
        for i in range(len(Cart_List)):
            Item_GL_1 = QtWidgets.QWidget(self.Main_QW)
            Item_GL_1.setMinimumSize(QtCore.QSize(900, 370))
            Item_GL_1.setMaximumSize(QtCore.QSize(1000, 350))
            Item_GL_1.setStyleSheet("background-color:White;")
            Item_GL_1.setObjectName("Item_GL_1")
            gridLayout_2 = QtWidgets.QGridLayout(Item_GL_1)
            gridLayout_2.setContentsMargins(30, 30, 30, 30)
            gridLayout_2.setObjectName("gridLayout_2")
            Description = QtWidgets.QWidget(Item_GL_1)
            Description.setStyleSheet("background-color: rgb(243, 243, 243);\n"
    "")
            Description.setObjectName("Description")
            verticalLayout_2 = QtWidgets.QVBoxLayout(Description)
            verticalLayout_2.setObjectName("verticalLayout_2")
            Name = QtWidgets.QToolButton(Description)
            Name.setMinimumSize(QtCore.QSize(719, 0))
            Name.setLayoutDirection(QtCore.Qt.LeftToRight)
            Name.setStyleSheet("background-color:rgb(0,0,0,0);")
            Name.setObjectName("Name")
            verticalLayout_2.addWidget(Name, 0, QtCore.Qt.AlignHCenter)
            Rate = QtWidgets.QToolButton(Description)
            Rate.setMinimumSize(QtCore.QSize(90, 0))
            Rate.setStyleSheet("background-color: rgb(0,0,0,0)")
            Rate.setIcon(self.icon3)
            Rate.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
            Rate.setObjectName("Rate")
            verticalLayout_2.addWidget(Rate, 0, QtCore.Qt.AlignHCenter)
            Amount = QtWidgets.QLabel(Description)
            Amount.setLayoutDirection(QtCore.Qt.LeftToRight)
            Amount.setObjectName("Amount")
            verticalLayout_2.addWidget(Amount, 0, QtCore.Qt.AlignHCenter)
            gridLayout_2.addWidget(Description, 3, 1, 1, 1)
            verticalLayout_3 = QtWidgets.QVBoxLayout()
            verticalLayout_3.setObjectName("verticalLayout_3")
            toolButton = QtWidgets.QToolButton(Item_GL_1)
            toolButton.setMinimumSize(QtCore.QSize(100, 150))
            icon4 = QtGui.QIcon()
            icon4.addPixmap(QtGui.QPixmap("../Images/tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            toolButton.setIcon(icon4)
            toolButton.setIconSize(QtCore.QSize(60, 60))
            toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
            toolButton.setObjectName("toolButton")
            toolButton.setCheckable(True)
            self.btn_grp.addButton(toolButton)
            
            verticalLayout_3.addWidget(toolButton)
            spinBox = QtWidgets.QSpinBox(Item_GL_1)
            spinBox.setObjectName("spinBox")
    
            spinBox.setMaximum(int(Cart_List[i].Item.Count)+int(Cart_List[i].Count))
            spinBox.setValue(int(Cart_List[i].Count))
            self.spinbox_list.append(spinBox)
            verticalLayout_3.addWidget(spinBox)
            gridLayout_2.addLayout(verticalLayout_3, 3, 0, 1, 1)
            Picture_1 = QtWidgets.QToolButton(Item_GL_1)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(Picture_1.sizePolicy().hasHeightForWidth())
            Picture_1.setSizePolicy(sizePolicy)
            Picture_1.setMinimumSize(QtCore.QSize(800, 150))
            Picture_1.setMaximumSize(QtCore.QSize(1000, 150))
            Picture_1.setLayoutDirection(QtCore.Qt.RightToLeft)
            Picture_1.setAutoFillBackground(False)
            Picture_1.setStyleSheet("background-color:rgb(0,0,0,0);")
            Picture_1.setText("")
            icon5 = QtGui.QIcon()
            icon5.addPixmap(QtGui.QPixmap("../Images/UserUploaded imgs/Product.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            Picture_1.setIcon(icon5)
            Picture_1.setIconSize(QtCore.QSize(200, 200))
            Picture_1.setObjectName("Picture_1")
            Name.setText(_translate("Main_Customer", Cart_List[i].Item.Product_ID.Name))
            Rate.setText(_translate("Main_Customer", f"{0} / 5"))
            Amount.setText(_translate("Main_Customer", f"<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">ریال</span><span style=\" font-size:12pt; font-weight:600;\"> {Cart_List[i].Item.Cost} </span></p></body></html>"))
            toolButton.setText(_translate("Main_Customer", "تایید"))
            gridLayout_2.addWidget(Picture_1, 0, 1, 1, 1)
            self.verticalLayout_4.addWidget(Item_GL_1)
            
    def confirmbutton(self,btn):
        with open('../DataBase/Items.pkl', 'rb') as handle:
            Items_list = pickle.load(handle)
        self.Items_list = Items_list

        Cart_List = self.c.Cart
        prev = Cart_List[-1*(self.btn_grp.checkedId()+1)-1].Count
        Cart_List[-1*(self.btn_grp.checkedId()+1)-1].Count = int(self.spinbox_list[-1*(self.btn_grp.checkedId()+1)-1].text())
        if int(prev)>= int(self.spinbox_list[-1*(self.btn_grp.checkedId()+1)-1].text()):
            Cart_List[-1*(self.btn_grp.checkedId()+1)-1].Item.Count += (int(prev)-int(self.spinbox_list[-1*(self.btn_grp.checkedId()+1)-1].text()))
            for i in range(len(self.Items_list)):
                if Cart_List[-1*(self.btn_grp.checkedId()+1)-1].Item.ID == self.Items_list[i].ID:
                    self.Items_list[i] = Cart_List[-1*(self.btn_grp.checkedId()+1)-1].Item
        else:
            Cart_List[-1*(self.btn_grp.checkedId()+1)-1].Item.Count -= (int(self.spinbox_list[-1*(self.btn_grp.checkedId()+1)-1].text())-int(prev))
            for i in range(len(self.Items_list)):
                if Cart_List[-1*(self.btn_grp.checkedId()+1)-1].Item.ID == self.Items_list[i].ID:
                    self.Items_list[i] = Cart_List[-1*(self.btn_grp.checkedId()+1)-1].Item

        with open('../DataBase/Items.pkl', 'wb') as handle:
                pickle.dump(self.Items_list, handle)
        
        if self.spinbox_list[-1*(self.btn_grp.checkedId()+1)-1].text() == '0':
            del Cart_List[-1*(self.btn_grp.checkedId()+1)-1]
        #print(len(Cart_List))
        with open('../DataBase/Customers.pkl', 'rb') as handle:
            Customers_List = pickle.load(handle)

        for i,C in enumerate(Customers_List):
            if self.c.Email == C.Email:
                Customers_List[i] = self.c
        with open('../DataBase/Customers.pkl', 'wb') as handle:
            pickle.dump(Customers_List, handle)
        with open('../DataBase/logined.pkl', 'wb') as handle:
            pickle.dump(self.c, handle)
        self.refresh()

    def sumofcost(self):
        Cart_List = self.c.Cart
        sum = 0
        for i in Cart_List:
            sum += int(i.Count) * int(i.Cost)
        return str(sum)
    
    def refresh(self):
        self.Page = QtWidgets.QWidget()
        self.ui = Ui_Main_Customer()
        self.ui.setupUi(self.Page)
        
        self.page.hide()
        self.Page.show()

    def sumofcart(self):
        sum = 0
        for By in self.c.Cart:
            sum += (By.Cost * By.Count)
        return sum
