# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Customer_Report.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pickle
import os
from datetime import datetime
dir_path = os.path.dirname(os.path.realpath(__file__))
os.chdir(dir_path)

class Ui_Main_Customer(object):
    def setupUi(self, Main_Customer):

        self.page = Main_Customer
        Main_Customer.setObjectName("Main_Customer")
        Main_Customer.resize(1038, 570)
        Main_Customer.setMinimumSize(QtCore.QSize(1038, 570))
        Main_Customer.setMaximumSize(QtCore.QSize(1038, 570))
        self.verticalLayout = QtWidgets.QVBoxLayout(Main_Customer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Header = QtWidgets.QHBoxLayout()
        self.Header.setObjectName("Header")
        self.pushButton_2 = QtWidgets.QPushButton(Main_Customer)
        self.pushButton_2.setMinimumSize(QtCore.QSize(73, 69))
        self.pushButton_2.setMaximumSize(QtCore.QSize(73, 69))
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Images/Back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_2.setObjectName("pushButton_2")
        self.Header.addWidget(self.pushButton_2)
        self.Exit_PB = QtWidgets.QPushButton(Main_Customer)
        self.Exit_PB.setMinimumSize(QtCore.QSize(73, 69))
        self.Exit_PB.setMaximumSize(QtCore.QSize(73, 69))
        self.Exit_PB.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Images/Exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Exit_PB.setIcon(icon1)
        self.Exit_PB.setIconSize(QtCore.QSize(60, 60))
        self.Exit_PB.setAutoDefault(False)
        self.Exit_PB.setDefault(False)
        self.Exit_PB.setFlat(False)
        self.Exit_PB.setObjectName("Exit_PB")
        self.Header.addWidget(self.Exit_PB)
        self.Cart_PB = QtWidgets.QPushButton(Main_Customer)
        self.Cart_PB.setMinimumSize(QtCore.QSize(73, 69))
        self.Cart_PB.setMaximumSize(QtCore.QSize(150, 69))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Cart_PB.setFont(font)
        self.Cart_PB.setStyleSheet("color: #f08804;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Images/Cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Cart_PB.setIcon(icon2)
        self.Cart_PB.setIconSize(QtCore.QSize(60, 60))
        self.Cart_PB.setObjectName("Cart_PB")
        self.Header.addWidget(self.Cart_PB)
        self.Wishlist_PB = QtWidgets.QPushButton(Main_Customer)
        self.Wishlist_PB.setMinimumSize(QtCore.QSize(73, 69))
        self.Wishlist_PB.setMaximumSize(QtCore.QSize(73, 69))
        self.Wishlist_PB.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Images/WishList.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Wishlist_PB.setIcon(icon3)
        self.Wishlist_PB.setIconSize(QtCore.QSize(60, 60))
        self.Wishlist_PB.setObjectName("Wishlist_PB")
        self.Header.addWidget(self.Wishlist_PB)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Header.addItem(spacerItem)
        self.Specs_GL = QtWidgets.QGridLayout()
        self.Specs_GL.setObjectName("Specs_GL")
        self.Email_var = QtWidgets.QLabel(Main_Customer)
        self.Email_var.setObjectName("Email_var")
        self.Specs_GL.addWidget(self.Email_var, 1, 1, 1, 1)
        self.Email_LB = QtWidgets.QLabel(Main_Customer)
        self.Email_LB.setObjectName("Email_LB")
        self.Specs_GL.addWidget(self.Email_LB, 1, 2, 1, 1)
        self.ID_LB = QtWidgets.QLabel(Main_Customer)
        self.ID_LB.setObjectName("ID_LB")
        self.Specs_GL.addWidget(self.ID_LB, 2, 2, 1, 1)
        self.ID_var = QtWidgets.QLabel(Main_Customer)
        self.ID_var.setObjectName("ID_var")
        self.Specs_GL.addWidget(self.ID_var, 2, 1, 1, 1)
        self.Name_var = QtWidgets.QLabel(Main_Customer)
        self.Name_var.setObjectName("Name_var")
        self.Specs_GL.addWidget(self.Name_var, 0, 1, 1, 1)
        self.Name_LB = QtWidgets.QLabel(Main_Customer)
        self.Name_LB.setObjectName("Name_LB")
        self.Specs_GL.addWidget(self.Name_LB, 0, 2, 1, 1)
        self.Header.addLayout(self.Specs_GL)
        self.Header_HL = QtWidgets.QHBoxLayout()
        self.Header_HL.setObjectName("Header_HL")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Header_HL.addItem(spacerItem1)
        self.Unit_LB = QtWidgets.QLabel(Main_Customer)
        self.Unit_LB.setMaximumSize(QtCore.QSize(500, 50))
        self.Unit_LB.setObjectName("Unit_LB")
        self.Header_HL.addWidget(self.Unit_LB, 0, QtCore.Qt.AlignRight)
        self.Money_var = QtWidgets.QLabel(Main_Customer)
        self.Money_var.setMaximumSize(QtCore.QSize(500, 50))
        self.Money_var.setObjectName("Money_var")
        self.Header_HL.addWidget(self.Money_var, 0, QtCore.Qt.AlignLeft)
        self.Bal_LB = QtWidgets.QLabel(Main_Customer)
        self.Bal_LB.setMaximumSize(QtCore.QSize(500, 50))
        self.Bal_LB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Bal_LB.setObjectName("Bal_LB")
        self.Header_HL.addWidget(self.Bal_LB, 0, QtCore.Qt.AlignRight)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Header_HL.addItem(spacerItem2)
        self.Shop_Name_LB = QtWidgets.QLabel(Main_Customer)
        self.Shop_Name_LB.setMaximumSize(QtCore.QSize(500, 50))
        self.Shop_Name_LB.setObjectName("Shop_Name_LB")
        self.Header_HL.addWidget(self.Shop_Name_LB)
        self.Header_HL.setStretch(0, 4)
        self.Header_HL.setStretch(4, 4)
        self.Header.addLayout(self.Header_HL)
        self.Header.setStretch(6, 1)
        self.verticalLayout.addLayout(self.Header)
        self.line = QtWidgets.QFrame(Main_Customer)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.Main = QtWidgets.QGridLayout()
        self.Main.setObjectName("Main")
        self.Main_VL = QtWidgets.QVBoxLayout()
        self.Main_VL.setObjectName("Main_VL")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(30, 30, 30, 30)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Main_Customer)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 5, 1, 1, QtCore.Qt.AlignRight)
        self.dateEdit_2 = QtWidgets.QDateEdit(Main_Customer)
        self.dateEdit_2.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.dateEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout.addWidget(self.dateEdit_2, 0, 1, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(Main_Customer)
        self.dateEdit.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 0, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(Main_Customer)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.Main_VL.addLayout(self.gridLayout)
        self.pushButton = QtWidgets.QPushButton(Main_Customer)
        self.pushButton.setStyleSheet("background: #f0c14b;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.Main_VL.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)
        self.tableWidget = QtWidgets.QTableWidget(Main_Customer)
        self.tableWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        

        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)

        self.Main_VL.addWidget(self.tableWidget)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(30, 15, 30, 15)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(Main_Customer)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 1, 1, 1, QtCore.Qt.AlignRight)
        self.label_6 = QtWidgets.QLabel(Main_Customer)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 2, 1, 1, QtCore.Qt.AlignRight)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Main_Customer)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 2, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 3, 1, 1)
        self.Main_VL.addLayout(self.gridLayout_3)
        self.Main.addLayout(self.Main_VL, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.Main)

        ### Header ###
        with open('../DataBase/logined.pkl', 'rb') as handle:
            c = pickle.load(handle)
        self.c = c
        self.pushButton_2.clicked.connect(self.back)  #pushButton_2 = Back_PB
        self.Exit_PB.clicked.connect(self.logout)
        self.Wishlist_PB.clicked.connect(self.wishlist)
        self.Cart_PB.clicked.connect(self.cart)
        self.Email_var.setText(c.Email)
        self.ID_var.setText(c.ID)
        self.Name_var.setText(c.Name)
        self.Money_var.setText(str(c.Wallet))
        self.Cart_PB.setText(str(self.sumofcart()))
        ### Main ###
        self.pushButton.clicked.connect(self.call)

        self.retranslateUi(Main_Customer)
        QtCore.QMetaObject.connectSlotsByName(Main_Customer)

    def retranslateUi(self, Main_Customer):
        _translate = QtCore.QCoreApplication.translate
        Main_Customer.setWindowTitle(_translate("Main_Customer", "Report"))
        self.Email_LB.setText(_translate("Main_Customer", "ایمیل :"))
        self.ID_LB.setText(_translate("Main_Customer", "آیدی :"))
        self.Name_LB.setText(_translate("Main_Customer", "نام : "))
        self.Unit_LB.setText(_translate("Main_Customer", "ریال"))
        self.Bal_LB.setText(_translate("Main_Customer", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">: موجودی</span></p></body></html>"))
        self.Shop_Name_LB.setText(_translate("Main_Customer", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">فروشگاه من</span></p></body></html>"))
        self.label.setText(_translate("Main_Customer", "از :"))
        self.label_2.setText(_translate("Main_Customer", "تا:"))
        self.pushButton.setText(_translate("Main_Customer", "محاسبه"))
        
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Main_Customer", "کد مرسوله"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Main_Customer", "قیمت"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Main_Customer", "تاریخ"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Main_Customer", "تعداد محصولات"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_7.setText(_translate("Main_Customer", "<html><head/><body><p><span style=\" font-size:10pt;\">ریال</span></p></body></html>"))
        
        self.label_5.setText(_translate("Main_Customer", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">:خرج شده</span><br/></p></body></html>"))

### Header ###
    def logout(self):
        with open('../DataBase/logined.pkl', 'wb') as handle:
            pickle.dump(0, handle)
        self.page.close()
        os.system('python Main.py')

    def wishlist(self):
        from Customer_WishList import Ui_Main_Customer
        self.WishListPage = QtWidgets.QWidget()
        self.ui = Ui_Main_Customer()
        self.ui.setupUi(self.WishListPage)
        
        self.page.hide()
        self.WishListPage.show()

    def cart(self):
        from Customer_Cart import Ui_Main_Customer
        self.CartPage = QtWidgets.QWidget()
        self.ui = Ui_Main_Customer()
        self.ui.setupUi(self.CartPage)
        
        self.page.hide()
        self.CartPage.show()
    
    def back(self):
        from Customer_Main import Ui_Main_Customer
        self.MainPage = QtWidgets.QWidget()
        self.ui = Ui_Main_Customer()
        self.ui.setupUi(self.MainPage)
        
        self.page.hide()
        self.MainPage.show()
    ### Main ###
    def call(self):
        start = self.dateEdit.text()
        start = datetime.strptime(start,"%d/%m/%Y")
        end = self.dateEdit_2.text()
        end = datetime.strptime(end,"%d/%m/%Y")
        list_of_buys = []
        with open('../DataBase/ListOfBuys.pkl', 'rb') as handle:
            listofbuys = pickle.load(handle)
        for lb in listofbuys:
            if start <= lb.Date <= end:
                list_of_buys.append(lb)
        self.tableWidget.setRowCount(len(list_of_buys))
        sumofprices = 0
        for i, lb in enumerate(list_of_buys):
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setVerticalHeaderItem(i, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 1, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 2, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 3, item)
            

            item = self.tableWidget.verticalHeaderItem(i)
            item.setText(str(i+1))

            item = self.tableWidget.item(i, 0)
            item.setText(lb.ID)
            item = self.tableWidget.item(i, 1)
            item.setText(str(lb.totalcost))
            item = self.tableWidget.item(i, 2)
            item.setText(str(lb.Date))
            item = self.tableWidget.item(i, 3)
            item.setText(str(lb.count))
            sumofprices += lb.totalcost

        self.label_6.setText(f"<html><head/><body><p><span style=\" font-size:10pt;\">{sumofprices}</span></p></body></html>")
    
    def sumofcart(self):
        sum = 0
        for By in self.c.Cart:
            sum += (By.Cost * By.Count)
        return sum

