# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Customer_Product.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main_Customer(object):
    def setupUi(self, Main_Customer):
        Main_Customer.setObjectName("Main_Customer")
        Main_Customer.resize(1038, 570)
        Main_Customer.setMinimumSize(QtCore.QSize(1038, 570))
        Main_Customer.setMaximumSize(QtCore.QSize(1038, 570))
        self.verticalLayout = QtWidgets.QVBoxLayout(Main_Customer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Header = QtWidgets.QHBoxLayout()
        self.Header.setObjectName("Header")
        self.Back_PB = QtWidgets.QPushButton(Main_Customer)
        self.Back_PB.setMinimumSize(QtCore.QSize(73, 69))
        self.Back_PB.setMaximumSize(QtCore.QSize(73, 69))
        self.Back_PB.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Images/Back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Back_PB.setIcon(icon)
        self.Back_PB.setIconSize(QtCore.QSize(60, 60))
        self.Back_PB.setObjectName("Back_PB")
        self.Header.addWidget(self.Back_PB)
        self.Exit_PB = QtWidgets.QPushButton(Main_Customer)
        self.Exit_PB.setMinimumSize(QtCore.QSize(73, 69))
        self.Exit_PB.setMaximumSize(QtCore.QSize(73, 69))
        self.Exit_PB.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Images/Exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Exit_PB.setIcon(icon1)
        self.Exit_PB.setIconSize(QtCore.QSize(60, 60))
        self.Exit_PB.setAutoDefault(False)
        self.Exit_PB.setDefault(False)
        self.Exit_PB.setFlat(False)
        self.Exit_PB.setObjectName("Exit_PB")
        self.Header.addWidget(self.Exit_PB)
        self.Cart_PB = QtWidgets.QPushButton(Main_Customer)
        self.Cart_PB.setMinimumSize(QtCore.QSize(73, 69))
        self.Cart_PB.setMaximumSize(QtCore.QSize(150, 69))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Cart_PB.setFont(font)
        self.Cart_PB.setStyleSheet("color: #f08804;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Images/Cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Cart_PB.setIcon(icon2)
        self.Cart_PB.setIconSize(QtCore.QSize(60, 60))
        self.Cart_PB.setObjectName("Cart_PB")
        self.Header.addWidget(self.Cart_PB)
        self.Wishlist_PB = QtWidgets.QPushButton(Main_Customer)
        self.Wishlist_PB.setMinimumSize(QtCore.QSize(73, 69))
        self.Wishlist_PB.setMaximumSize(QtCore.QSize(73, 69))
        self.Wishlist_PB.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Images/WishList.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Wishlist_PB.setIcon(icon3)
        self.Wishlist_PB.setIconSize(QtCore.QSize(60, 60))
        self.Wishlist_PB.setObjectName("Wishlist_PB")
        self.Header.addWidget(self.Wishlist_PB)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Header.addItem(spacerItem)
        self.Specs_GL = QtWidgets.QGridLayout()
        self.Specs_GL.setObjectName("Specs_GL")
        self.Email_var = QtWidgets.QLabel(Main_Customer)
        self.Email_var.setObjectName("Email_var")
        self.Specs_GL.addWidget(self.Email_var, 1, 1, 1, 1)
        self.Email_LB = QtWidgets.QLabel(Main_Customer)
        self.Email_LB.setObjectName("Email_LB")
        self.Specs_GL.addWidget(self.Email_LB, 1, 2, 1, 1)
        self.ID_LB = QtWidgets.QLabel(Main_Customer)
        self.ID_LB.setObjectName("ID_LB")
        self.Specs_GL.addWidget(self.ID_LB, 2, 2, 1, 1)
        self.ID_var = QtWidgets.QLabel(Main_Customer)
        self.ID_var.setObjectName("ID_var")
        self.Specs_GL.addWidget(self.ID_var, 2, 1, 1, 1)
        self.Name_var = QtWidgets.QLabel(Main_Customer)
        self.Name_var.setObjectName("Name_var")
        self.Specs_GL.addWidget(self.Name_var, 0, 1, 1, 1)
        self.Name_LB = QtWidgets.QLabel(Main_Customer)
        self.Name_LB.setObjectName("Name_LB")
        self.Specs_GL.addWidget(self.Name_LB, 0, 2, 1, 1)
        self.Header.addLayout(self.Specs_GL)
        self.Header_HL = QtWidgets.QHBoxLayout()
        self.Header_HL.setObjectName("Header_HL")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Header_HL.addItem(spacerItem1)
        self.Unit_LB = QtWidgets.QLabel(Main_Customer)
        self.Unit_LB.setMaximumSize(QtCore.QSize(500, 50))
        self.Unit_LB.setObjectName("Unit_LB")
        self.Header_HL.addWidget(self.Unit_LB, 0, QtCore.Qt.AlignRight)
        self.Money_var = QtWidgets.QLabel(Main_Customer)
        self.Money_var.setMaximumSize(QtCore.QSize(500, 50))
        self.Money_var.setObjectName("Money_var")
        self.Header_HL.addWidget(self.Money_var, 0, QtCore.Qt.AlignLeft)
        self.Bal_LB = QtWidgets.QLabel(Main_Customer)
        self.Bal_LB.setMaximumSize(QtCore.QSize(500, 50))
        self.Bal_LB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Bal_LB.setObjectName("Bal_LB")
        self.Header_HL.addWidget(self.Bal_LB, 0, QtCore.Qt.AlignRight)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Header_HL.addItem(spacerItem2)
        self.Shop_Name_LB = QtWidgets.QLabel(Main_Customer)
        self.Shop_Name_LB.setMaximumSize(QtCore.QSize(500, 50))
        self.Shop_Name_LB.setObjectName("Shop_Name_LB")
        self.Header_HL.addWidget(self.Shop_Name_LB)
        self.Header_HL.setStretch(0, 4)
        self.Header_HL.setStretch(4, 4)
        self.Header.addLayout(self.Header_HL)
        self.Header.setStretch(6, 1)
        self.verticalLayout.addLayout(self.Header)
        self.line = QtWidgets.QFrame(Main_Customer)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.Main = QtWidgets.QGridLayout()
        self.Main.setObjectName("Main")
        self.Main_VL = QtWidgets.QVBoxLayout()
        self.Main_VL.setObjectName("Main_VL")
        self.Main_SA = QtWidgets.QScrollArea(Main_Customer)
        self.Main_SA.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Main_SA.setWidgetResizable(True)
        self.Main_SA.setObjectName("Main_SA")
        self.Main_QW = QtWidgets.QWidget()
        self.Main_QW.setGeometry(QtCore.QRect(0, -651, 989, 1105))
        self.Main_QW.setObjectName("Main_QW")
        self.gridLayout = QtWidgets.QGridLayout(self.Main_QW)
        self.gridLayout.setObjectName("gridLayout")
        self.Main_Line = QtWidgets.QFrame(self.Main_QW)
        self.Main_Line.setFrameShape(QtWidgets.QFrame.HLine)
        self.Main_Line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Main_Line.setObjectName("Main_Line")
        self.gridLayout.addWidget(self.Main_Line, 4, 0, 1, 1)
        self.Item_GL_1 = QtWidgets.QWidget(self.Main_QW)
        self.Item_GL_1.setMinimumSize(QtCore.QSize(900, 350))
        self.Item_GL_1.setMaximumSize(QtCore.QSize(1000, 350))
        self.Item_GL_1.setStyleSheet("background-color:White;")
        self.Item_GL_1.setObjectName("Item_GL_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Item_GL_1)
        self.gridLayout_2.setContentsMargins(30, 30, 30, 30)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Description = QtWidgets.QWidget(self.Item_GL_1)
        self.Description.setStyleSheet("background-color: rgb(243, 243, 243);\n"
"")
        self.Description.setObjectName("Description")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Description)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.Description)
        self.label.setMinimumSize(QtCore.QSize(600, 50))
        self.label.setMaximumSize(QtCore.QSize(800, 50))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignRight)
        self.Amount = QtWidgets.QLabel(self.Description)
        self.Amount.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Amount.setObjectName("Amount")
        self.verticalLayout_2.addWidget(self.Amount, 0, QtCore.Qt.AlignHCenter)
        self.toolButton = QtWidgets.QToolButton(self.Description)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Images/Add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon4)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton.setObjectName("toolButton")
        self.verticalLayout_2.addWidget(self.toolButton, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addWidget(self.Description, 0, 1, 1, 1)
        self.Picture_1 = QtWidgets.QToolButton(self.Item_GL_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Picture_1.sizePolicy().hasHeightForWidth())
        self.Picture_1.setSizePolicy(sizePolicy)
        self.Picture_1.setMinimumSize(QtCore.QSize(200, 150))
        self.Picture_1.setMaximumSize(QtCore.QSize(200, 150))
        self.Picture_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Picture_1.setAutoFillBackground(False)
        self.Picture_1.setStyleSheet("background-color:rgb(0,0,0,0);")
        self.Picture_1.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../Images/UserUploaded imgs/Product.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Picture_1.setIcon(icon5)
        self.Picture_1.setIconSize(QtCore.QSize(200, 200))
        self.Picture_1.setObjectName("Picture_1")
        self.gridLayout_2.addWidget(self.Picture_1, 0, 3, 1, 1)
        self.Rate_2 = QtWidgets.QToolButton(self.Item_GL_1)
        self.Rate_2.setMinimumSize(QtCore.QSize(90, 0))
        self.Rate_2.setStyleSheet("background-color: rgb(0,0,0,0)")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../Images/Comment.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Rate_2.setIcon(icon6)
        self.Rate_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Rate_2.setObjectName("Rate_2")
        self.gridLayout_2.addWidget(self.Rate_2, 2, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.Rate = QtWidgets.QToolButton(self.Item_GL_1)
        self.Rate.setMinimumSize(QtCore.QSize(90, 0))
        self.Rate.setStyleSheet("background-color: rgb(0,0,0,0)")
        self.Rate.setIcon(icon3)
        self.Rate.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Rate.setObjectName("Rate")
        self.gridLayout_2.addWidget(self.Rate, 1, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.Item_GL_1)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.Item_GL_1)
        self.label_2.setMinimumSize(QtCore.QSize(0, 50))
        self.label_2.setMaximumSize(QtCore.QSize(150, 500))
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.Item_GL_1, 0, 0, 1, 1)
        self.Seller_BL_1 = QtWidgets.QVBoxLayout()
        self.Seller_BL_1.setObjectName("Seller_BL_1")
        self.Seller_QW_1 = QtWidgets.QWidget(self.Main_QW)
        self.Seller_QW_1.setStyleSheet("background-color: rgb(248, 248, 248);")
        self.Seller_QW_1.setObjectName("Seller_QW_1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Seller_QW_1)
        self.gridLayout_3.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Seller_Cost_VL = QtWidgets.QVBoxLayout()
        self.Seller_Cost_VL.setObjectName("Seller_Cost_VL")
        self.Money_LB = QtWidgets.QLabel(self.Seller_QW_1)
        self.Money_LB.setMinimumSize(QtCore.QSize(150, 50))
        self.Money_LB.setObjectName("Money_LB")
        self.Seller_Cost_VL.addWidget(self.Money_LB)
        self.Amount_LB = QtWidgets.QLabel(self.Seller_QW_1)
        self.Amount_LB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Amount_LB.setObjectName("Amount_LB")
        self.Seller_Cost_VL.addWidget(self.Amount_LB, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_3.addLayout(self.Seller_Cost_VL, 0, 2, 1, 1)
        self.Buy_VL = QtWidgets.QVBoxLayout()
        self.Buy_VL.setObjectName("Buy_VL")
        self.Buy_PB = QtWidgets.QToolButton(self.Seller_QW_1)
        self.Buy_PB.setMinimumSize(QtCore.QSize(100, 150))
        self.Buy_PB.setIcon(icon4)
        self.Buy_PB.setIconSize(QtCore.QSize(60, 60))
        self.Buy_PB.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Buy_PB.setObjectName("Buy_PB")
        self.Buy_VL.addWidget(self.Buy_PB)
        self.Amount_SB = QtWidgets.QSpinBox(self.Seller_QW_1)
        self.Amount_SB.setObjectName("Amount_SB")
        self.Buy_VL.addWidget(self.Amount_SB)
        self.gridLayout_3.addLayout(self.Buy_VL, 0, 1, 1, 1)
        self.Seller_Name_LB = QtWidgets.QLabel(self.Seller_QW_1)
        self.Seller_Name_LB.setObjectName("Seller_Name_LB")
        self.gridLayout_3.addWidget(self.Seller_Name_LB, 0, 7, 1, 1, QtCore.Qt.AlignRight)
        self.Count_HL = QtWidgets.QHBoxLayout()
        self.Count_HL.setObjectName("Count_HL")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Count_HL.addItem(spacerItem3)
        self.Count_LB = QtWidgets.QLabel(self.Seller_QW_1)
        self.Count_LB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Count_LB.setObjectName("Count_LB")
        self.Count_HL.addWidget(self.Count_LB, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.Count_LB_Text = QtWidgets.QLabel(self.Seller_QW_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Count_LB_Text.sizePolicy().hasHeightForWidth())
        self.Count_LB_Text.setSizePolicy(sizePolicy)
        self.Count_LB_Text.setMinimumSize(QtCore.QSize(0, 0))
        self.Count_LB_Text.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Count_LB_Text.setObjectName("Count_LB_Text")
        self.Count_HL.addWidget(self.Count_LB_Text)
        self.gridLayout_3.addLayout(self.Count_HL, 0, 4, 1, 1)
        self.Seller_Name_LB_Text = QtWidgets.QLabel(self.Seller_QW_1)
        self.Seller_Name_LB_Text.setObjectName("Seller_Name_LB_Text")
        self.gridLayout_3.addWidget(self.Seller_Name_LB_Text, 0, 8, 1, 1, QtCore.Qt.AlignRight)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 5, 1, 1)
        self.Seller_BL_1.addWidget(self.Seller_QW_1)
        self.gridLayout.addLayout(self.Seller_BL_1, 6, 0, 1, 1)
        self.Comment_QW = QtWidgets.QWidget(self.Main_QW)
        self.Comment_QW.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.Comment_QW.setObjectName("Comment_QW")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Comment_QW)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_12 = QtWidgets.QLabel(self.Comment_QW)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 0, 0, 1, 1)
        self.toolButton1 = QtWidgets.QToolButton(self.Comment_QW)
        self.toolButton1.setIcon(icon6)
        self.toolButton1.setIconSize(QtCore.QSize(60, 60))
        self.toolButton1.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton1.setObjectName("toolButton1")
        self.gridLayout_5.addWidget(self.toolButton1, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.Comment_GL = QtWidgets.QWidget(self.Comment_QW)
        self.Comment_GL.setStyleSheet("background-color: rgb(224, 255, 255);")
        self.Comment_GL.setObjectName("Comment_GL")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.Comment_GL)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Comment_Name_LB = QtWidgets.QLabel(self.Comment_GL)
        self.Comment_Name_LB.setObjectName("Comment_Name_LB")
        self.gridLayout_6.addWidget(self.Comment_Name_LB, 0, 2, 1, 1, QtCore.Qt.AlignRight)
        self.Comment_Rate = QtWidgets.QLabel(self.Comment_GL)
        self.Comment_Rate.setObjectName("Comment_Rate")
        self.gridLayout_6.addWidget(self.Comment_Rate, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 0, 0, 1, 1)
        self.Comment_LB_Text = QtWidgets.QLabel(self.Comment_GL)
        self.Comment_LB_Text.setObjectName("Comment_LB_Text")
        self.gridLayout_6.addWidget(self.Comment_LB_Text, 1, 1, 1, 1, QtCore.Qt.AlignRight)
        self.Comment_LB = QtWidgets.QLabel(self.Comment_GL)
        self.Comment_LB.setObjectName("Comment_LB")
        self.gridLayout_6.addWidget(self.Comment_LB, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.Comment_Count = QtWidgets.QLabel(self.Comment_GL)
        self.Comment_Count.setObjectName("Comment_Count")
        self.gridLayout_6.addWidget(self.Comment_Count, 1, 2, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout_5.addWidget(self.Comment_GL, 3, 0, 1, 1)
        self.Comment_GL_2 = QtWidgets.QWidget(self.Comment_QW)
        self.Comment_GL_2.setStyleSheet("background-color: rgb(224, 255, 255);")
        self.Comment_GL_2.setObjectName("Comment_GL_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.Comment_GL_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.Comment_Name_LB_2 = QtWidgets.QLabel(self.Comment_GL_2)
        self.Comment_Name_LB_2.setObjectName("Comment_Name_LB_2")
        self.gridLayout_9.addWidget(self.Comment_Name_LB_2, 0, 2, 1, 1, QtCore.Qt.AlignRight)
        self.Comment_Rate_2 = QtWidgets.QLabel(self.Comment_GL_2)
        self.Comment_Rate_2.setObjectName("Comment_Rate_2")
        self.gridLayout_9.addWidget(self.Comment_Rate_2, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem6, 0, 0, 1, 1)
        self.Comment_LB_Text_2 = QtWidgets.QLabel(self.Comment_GL_2)
        self.Comment_LB_Text_2.setObjectName("Comment_LB_Text_2")
        self.gridLayout_9.addWidget(self.Comment_LB_Text_2, 1, 1, 1, 1, QtCore.Qt.AlignRight)
        self.Comment_LB_2 = QtWidgets.QLabel(self.Comment_GL_2)
        self.Comment_LB_2.setObjectName("Comment_LB_2")
        self.gridLayout_9.addWidget(self.Comment_LB_2, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.Comment_Count_2 = QtWidgets.QLabel(self.Comment_GL_2)
        self.Comment_Count_2.setObjectName("Comment_Count_2")
        self.gridLayout_9.addWidget(self.Comment_Count_2, 1, 2, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout_5.addWidget(self.Comment_GL_2, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.Comment_QW, 1, 0, 1, 1)
        self.Seller_QW_3 = QtWidgets.QWidget(self.Main_QW)
        self.Seller_QW_3.setStyleSheet("background-color: rgb(248, 248, 248);")
        self.Seller_QW_3.setObjectName("Seller_QW_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.Seller_QW_3)
        self.gridLayout_8.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.Seller_Cost_VL_3 = QtWidgets.QVBoxLayout()
        self.Seller_Cost_VL_3.setObjectName("Seller_Cost_VL_3")
        self.Money_LB_3 = QtWidgets.QLabel(self.Seller_QW_3)
        self.Money_LB_3.setMinimumSize(QtCore.QSize(150, 50))
        self.Money_LB_3.setObjectName("Money_LB_3")
        self.Seller_Cost_VL_3.addWidget(self.Money_LB_3)
        self.Amount_LB_3 = QtWidgets.QLabel(self.Seller_QW_3)
        self.Amount_LB_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Amount_LB_3.setObjectName("Amount_LB_3")
        self.Seller_Cost_VL_3.addWidget(self.Amount_LB_3, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_8.addLayout(self.Seller_Cost_VL_3, 0, 2, 1, 1)
        self.Buy_VL_3 = QtWidgets.QVBoxLayout()
        self.Buy_VL_3.setObjectName("Buy_VL_3")
        self.Buy_PB_3 = QtWidgets.QToolButton(self.Seller_QW_3)
        self.Buy_PB_3.setMinimumSize(QtCore.QSize(100, 150))
        self.Buy_PB_3.setIcon(icon4)
        self.Buy_PB_3.setIconSize(QtCore.QSize(60, 60))
        self.Buy_PB_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Buy_PB_3.setObjectName("Buy_PB_3")
        self.Buy_VL_3.addWidget(self.Buy_PB_3)
        self.Amount_SB_3 = QtWidgets.QSpinBox(self.Seller_QW_3)
        self.Amount_SB_3.setObjectName("Amount_SB_3")
        self.Buy_VL_3.addWidget(self.Amount_SB_3)
        self.gridLayout_8.addLayout(self.Buy_VL_3, 0, 1, 1, 1)
        self.Seller_Name_LB_3 = QtWidgets.QLabel(self.Seller_QW_3)
        self.Seller_Name_LB_3.setObjectName("Seller_Name_LB_3")
        self.gridLayout_8.addWidget(self.Seller_Name_LB_3, 0, 7, 1, 1, QtCore.Qt.AlignRight)
        self.Count_HL_3 = QtWidgets.QHBoxLayout()
        self.Count_HL_3.setObjectName("Count_HL_3")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Count_HL_3.addItem(spacerItem7)
        self.Count_LB_3 = QtWidgets.QLabel(self.Seller_QW_3)
        self.Count_LB_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Count_LB_3.setObjectName("Count_LB_3")
        self.Count_HL_3.addWidget(self.Count_LB_3, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.Count_LB_Text_3 = QtWidgets.QLabel(self.Seller_QW_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Count_LB_Text_3.sizePolicy().hasHeightForWidth())
        self.Count_LB_Text_3.setSizePolicy(sizePolicy)
        self.Count_LB_Text_3.setMinimumSize(QtCore.QSize(0, 0))
        self.Count_LB_Text_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Count_LB_Text_3.setObjectName("Count_LB_Text_3")
        self.Count_HL_3.addWidget(self.Count_LB_Text_3)
        self.gridLayout_8.addLayout(self.Count_HL_3, 0, 4, 1, 1)
        self.Seller_Name_LB_Text_3 = QtWidgets.QLabel(self.Seller_QW_3)
        self.Seller_Name_LB_Text_3.setObjectName("Seller_Name_LB_Text_3")
        self.gridLayout_8.addWidget(self.Seller_Name_LB_Text_3, 0, 8, 1, 1, QtCore.Qt.AlignRight)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem8, 0, 5, 1, 1)
        self.gridLayout.addWidget(self.Seller_QW_3, 5, 0, 1, 1)
        self.Main_SA.setWidget(self.Main_QW)
        self.Main_VL.addWidget(self.Main_SA)
        self.Main.addLayout(self.Main_VL, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.Main)

        self.retranslateUi(Main_Customer)
        QtCore.QMetaObject.connectSlotsByName(Main_Customer)

    def retranslateUi(self, Main_Customer):
        _translate = QtCore.QCoreApplication.translate
        Main_Customer.setWindowTitle(_translate("Main_Customer", "Form"))
        self.Cart_PB.setText(_translate("Main_Customer", "Count"))
        self.Email_var.setText(_translate("Main_Customer", "Email"))
        self.Email_LB.setText(_translate("Main_Customer", "ایمیل :"))
        self.ID_LB.setText(_translate("Main_Customer", "آیدی :"))
        self.ID_var.setText(_translate("Main_Customer", "ID"))
        self.Name_var.setText(_translate("Main_Customer", "Name"))
        self.Name_LB.setText(_translate("Main_Customer", "نام : "))
        self.Unit_LB.setText(_translate("Main_Customer", "ریال"))
        self.Money_var.setText(_translate("Main_Customer", "<html><head/><body><p><span style=\" font-size:10pt;\">Money</span></p></body></html>"))
        self.Bal_LB.setText(_translate("Main_Customer", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">: موجودی</span></p></body></html>"))
        self.Shop_Name_LB.setText(_translate("Main_Customer", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">فروشگاه من</span></p></body></html>"))
        self.label.setText(_translate("Main_Customer", "<html><head/><body><p align=\"right\"><span style=\" font-size:18pt; font-weight:600; color:#4c4c4c;\">Name</span></p></body></html>"))
        self.Amount.setText(_translate("Main_Customer", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">ریال</span><span style=\" font-size:12pt; font-weight:600;\"> Amount</span></p></body></html>"))
        self.toolButton.setText(_translate("Main_Customer", "افزودن به لیست\n"
"علاقه مندی ها"))
        self.Rate_2.setText(_translate("Main_Customer", "Comments"))
        self.Rate.setText(_translate("Main_Customer", "Rate / 5"))
        self.label_3.setText(_translate("Main_Customer", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">Description Text</span></p></body></html>"))
        self.label_2.setText(_translate("Main_Customer", "<html><head/><body><p align=\"right\"><span style=\" font-size:14pt; font-weight:600;\"> : مشخصات</span></p></body></html>"))
        self.Money_LB.setText(_translate("Main_Customer", "قیمت: "))
        self.Amount_LB.setText(_translate("Main_Customer", "<html><head/><body><p align=\"right\">ریال Amount</p></body></html>"))
        self.Buy_PB.setText(_translate("Main_Customer", "اضافه به سبد\n"
"خرید"))
        self.Seller_Name_LB.setText(_translate("Main_Customer", "Seller_Name"))
        self.Count_LB.setText(_translate("Main_Customer", "<html><head/><body><p align=\"right\">Count</p></body></html>"))
        self.Count_LB_Text.setText(_translate("Main_Customer", "تعداد: "))
        self.Seller_Name_LB_Text.setText(_translate("Main_Customer", "نام فروشنده: "))
        self.label_12.setText(_translate("Main_Customer", "<html><head/><body><p align=\"right\"><span style=\" font-size:20pt; font-weight:600;\">نظرات</span></p></body></html>"))
        self.toolButton1.setText(_translate("Main_Customer", "ثبت نظر"))
        self.Comment_Name_LB.setText(_translate("Main_Customer", "Name"))
        self.Comment_Rate.setText(_translate("Main_Customer", "نمره:  Rate/5"))
        self.Comment_LB_Text.setText(_translate("Main_Customer", "نظر :"))
        self.Comment_LB.setText(_translate("Main_Customer", "Comment"))
        self.Comment_Count.setText(_translate("Main_Customer", "Count"))
        self.Comment_Name_LB_2.setText(_translate("Main_Customer", "Name"))
        self.Comment_Rate_2.setText(_translate("Main_Customer", "نمره:  Rate/5"))
        self.Comment_LB_Text_2.setText(_translate("Main_Customer", "نظر :"))
        self.Comment_LB_2.setText(_translate("Main_Customer", "Comment"))
        self.Comment_Count_2.setText(_translate("Main_Customer", "Count"))
        self.Money_LB_3.setText(_translate("Main_Customer", "قیمت: "))
        self.Amount_LB_3.setText(_translate("Main_Customer", "<html><head/><body><p align=\"right\">ریال Amount</p></body></html>"))
        self.Buy_PB_3.setText(_translate("Main_Customer", "اضافه به سبد\n"
"خرید"))
        self.Seller_Name_LB_3.setText(_translate("Main_Customer", "Seller_Name"))
        self.Count_LB_3.setText(_translate("Main_Customer", "<html><head/><body><p align=\"right\">Count</p></body></html>"))
        self.Count_LB_Text_3.setText(_translate("Main_Customer", "تعداد: "))
        self.Seller_Name_LB_Text_3.setText(_translate("Main_Customer", "نام فروشنده: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main_Customer = QtWidgets.QWidget()
    ui = Ui_Main_Customer()
    ui.setupUi(Main_Customer)
    Main_Customer.show()
    sys.exit(app.exec_())

