# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Seller_Add.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import os
dir_path = os.path.dirname(os.path.realpath(__file__))
os.chdir(dir_path)

class Ui_Main_Customer(object):
    def setupUi(self, Main_Customer):
        Main_Customer.setObjectName("Main_Customer")
        Main_Customer.resize(1280, 720)
        Main_Customer.setMinimumSize(QtCore.QSize(1280, 720))
        Main_Customer.setMaximumSize(QtCore.QSize(1280, 720))
        self.verticalLayout = QtWidgets.QVBoxLayout(Main_Customer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Header_2 = QtWidgets.QHBoxLayout()
        self.Header_2.setObjectName("Header_2")
        self.pushButton_3 = QtWidgets.QPushButton(Main_Customer)
        self.pushButton_3.setMinimumSize(QtCore.QSize(87, 87))
        self.pushButton_3.setMaximumSize(QtCore.QSize(9999, 9999))
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Images/Back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_3.setObjectName("pushButton_3")
        self.Header_2.addWidget(self.pushButton_3)
        self.Exit_PB_2 = QtWidgets.QPushButton(Main_Customer)
        self.Exit_PB_2.setMinimumSize(QtCore.QSize(87, 87))
        self.Exit_PB_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Images/Exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Exit_PB_2.setIcon(icon1)
        self.Exit_PB_2.setIconSize(QtCore.QSize(60, 60))
        self.Exit_PB_2.setAutoDefault(False)
        self.Exit_PB_2.setDefault(False)
        self.Exit_PB_2.setFlat(False)
        self.Exit_PB_2.setObjectName("Exit_PB_2")
        self.Header_2.addWidget(self.Exit_PB_2)
        self.Wishlist_PB_2 = QtWidgets.QPushButton(Main_Customer)
        self.Wishlist_PB_2.setMinimumSize(QtCore.QSize(150, 0))
        self.Wishlist_PB_2.setMaximumSize(QtCore.QSize(200, 999))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Images/Comment.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Wishlist_PB_2.setIcon(icon2)
        self.Wishlist_PB_2.setIconSize(QtCore.QSize(60, 60))
        self.Wishlist_PB_2.setObjectName("Wishlist_PB_2")
        self.Header_2.addWidget(self.Wishlist_PB_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Header_2.addItem(spacerItem)
        self.Specs_GL_2 = QtWidgets.QGridLayout()
        self.Specs_GL_2.setObjectName("Specs_GL_2")
        self.ID_LB_2 = QtWidgets.QLabel(Main_Customer)
        self.ID_LB_2.setObjectName("ID_LB_2")
        self.Specs_GL_2.addWidget(self.ID_LB_2, 3, 2, 1, 1)
        self.ID_var_2 = QtWidgets.QLabel(Main_Customer)
        self.ID_var_2.setObjectName("ID_var_2")
        self.Specs_GL_2.addWidget(self.ID_var_2, 3, 1, 1, 1)
        self.Email_var_2 = QtWidgets.QLabel(Main_Customer)
        self.Email_var_2.setObjectName("Email_var_2")
        self.Specs_GL_2.addWidget(self.Email_var_2, 1, 1, 1, 1)
        self.Email_LB_2 = QtWidgets.QLabel(Main_Customer)
        self.Email_LB_2.setObjectName("Email_LB_2")
        self.Specs_GL_2.addWidget(self.Email_LB_2, 1, 2, 1, 1)
        self.Name_var_2 = QtWidgets.QLabel(Main_Customer)
        self.Name_var_2.setObjectName("Name_var_2")
        self.Specs_GL_2.addWidget(self.Name_var_2, 0, 1, 1, 1)
        self.Name_LB_2 = QtWidgets.QLabel(Main_Customer)
        self.Name_LB_2.setObjectName("Name_LB_2")
        self.Specs_GL_2.addWidget(self.Name_LB_2, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(Main_Customer)
        self.label_4.setObjectName("label_4")
        self.Specs_GL_2.addWidget(self.label_4, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Main_Customer)
        self.label_5.setObjectName("label_5")
        self.Specs_GL_2.addWidget(self.label_5, 2, 2, 1, 1, QtCore.Qt.AlignRight)
        self.Header_2.addLayout(self.Specs_GL_2)
        self.Header_HL_2 = QtWidgets.QHBoxLayout()
        self.Header_HL_2.setObjectName("Header_HL_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Header_HL_2.addItem(spacerItem1)
        self.Unit_LB_2 = QtWidgets.QLabel(Main_Customer)
        self.Unit_LB_2.setMaximumSize(QtCore.QSize(500, 50))
        self.Unit_LB_2.setObjectName("Unit_LB_2")
        self.Header_HL_2.addWidget(self.Unit_LB_2, 0, QtCore.Qt.AlignRight)
        self.Money_var_2 = QtWidgets.QLabel(Main_Customer)
        self.Money_var_2.setMaximumSize(QtCore.QSize(500, 50))
        self.Money_var_2.setObjectName("Money_var_2")
        self.Header_HL_2.addWidget(self.Money_var_2, 0, QtCore.Qt.AlignLeft)
        self.Bal_LB_2 = QtWidgets.QLabel(Main_Customer)
        self.Bal_LB_2.setMaximumSize(QtCore.QSize(500, 50))
        self.Bal_LB_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Bal_LB_2.setObjectName("Bal_LB_2")
        self.Header_HL_2.addWidget(self.Bal_LB_2, 0, QtCore.Qt.AlignRight)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Header_HL_2.addItem(spacerItem2)
        self.Shop_Name_LB_2 = QtWidgets.QLabel(Main_Customer)
        self.Shop_Name_LB_2.setMaximumSize(QtCore.QSize(500, 50))
        self.Shop_Name_LB_2.setObjectName("Shop_Name_LB_2")
        self.Header_HL_2.addWidget(self.Shop_Name_LB_2)
        self.Header_HL_2.setStretch(0, 4)
        self.Header_HL_2.setStretch(4, 4)
        self.Header_2.addLayout(self.Header_HL_2)
        self.Header_2.setStretch(5, 1)
        self.verticalLayout.addLayout(self.Header_2)
        self.line = QtWidgets.QFrame(Main_Customer)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.Main = QtWidgets.QGridLayout()
        self.Main.setObjectName("Main")
        self.Main_VL = QtWidgets.QVBoxLayout()
        self.Main_VL.setObjectName("Main_VL")
        self.scrollArea = QtWidgets.QScrollArea(Main_Customer)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1231, 1306))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.toolButton_4 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_4.sizePolicy().hasHeightForWidth())
        self.toolButton_4.setSizePolicy(sizePolicy)
        self.toolButton_4.setMinimumSize(QtCore.QSize(107, 277))
        self.toolButton_4.setMaximumSize(QtCore.QSize(107, 277))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Images/Report.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon3)
        self.toolButton_4.setIconSize(QtCore.QSize(200, 200))
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_4.setObjectName("toolButton_4")
        self.horizontalLayout.addWidget(self.toolButton_4, 0, QtCore.Qt.AlignHCenter)
        self.toolButton_3 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_3.sizePolicy().hasHeightForWidth())
        self.toolButton_3.setSizePolicy(sizePolicy)
        self.toolButton_3.setMinimumSize(QtCore.QSize(107, 277))
        self.toolButton_3.setMaximumSize(QtCore.QSize(107, 277))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Images/Cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon4)
        self.toolButton_3.setIconSize(QtCore.QSize(90, 100))
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout.addWidget(self.toolButton_3, 0, QtCore.Qt.AlignHCenter)
        self.toolButton = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setMinimumSize(QtCore.QSize(107, 277))
        self.toolButton.setMaximumSize(QtCore.QSize(107, 277))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../Images/Product.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon5)
        self.toolButton.setIconSize(QtCore.QSize(100, 100))
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton, 0, QtCore.Qt.AlignHCenter)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(10, 30, 10, 30)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.gridWidget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gridWidget_2.setStyleSheet("")
        self.gridWidget_2.setObjectName("gridWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridWidget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.toolButton_2 = QtWidgets.QToolButton(self.gridWidget_2)
        self.toolButton_2.setMinimumSize(QtCore.QSize(0, 0))
        self.toolButton_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../Images/Add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon6)
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout_2.addWidget(self.toolButton_2, 4, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.label_3 = QtWidgets.QLabel(self.gridWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 2, 1, 1, QtCore.Qt.AlignRight)
        self.lineEdit = QtWidgets.QLineEdit(self.gridWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridWidget_2)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 100))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 2, 1, 1, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.gridWidget_2)
        self.Item_GL_1 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.Item_GL_1.setMinimumSize(QtCore.QSize(900, 350))
        self.Item_GL_1.setMaximumSize(QtCore.QSize(1000, 350))
        self.Item_GL_1.setStyleSheet("background-color:White;")
        self.Item_GL_1.setObjectName("Item_GL_1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Item_GL_1)
        self.gridLayout_3.setContentsMargins(30, 30, 30, 30)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Description = QtWidgets.QWidget(self.Item_GL_1)
        self.Description.setStyleSheet("background-color: rgb(243, 243, 243);\n"
"")
        self.Description.setObjectName("Description")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Description)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Name = QtWidgets.QToolButton(self.Description)
        self.Name.setMinimumSize(QtCore.QSize(719, 0))
        self.Name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Name.setStyleSheet("background-color:rgb(0,0,0,0);")
        self.Name.setObjectName("Name")
        self.verticalLayout_3.addWidget(self.Name, 0, QtCore.Qt.AlignHCenter)
        self.Rate = QtWidgets.QToolButton(self.Description)
        self.Rate.setMinimumSize(QtCore.QSize(90, 0))
        self.Rate.setStyleSheet("background-color: rgb(0,0,0,0)")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../Images/WishList.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Rate.setIcon(icon7)
        self.Rate.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Rate.setObjectName("Rate")
        self.verticalLayout_3.addWidget(self.Rate, 0, QtCore.Qt.AlignHCenter)
        self.Amount = QtWidgets.QLabel(self.Description)
        self.Amount.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Amount.setObjectName("Amount")
        self.verticalLayout_3.addWidget(self.Amount, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_3.addWidget(self.Description, 1, 1, 1, 1)
        self.Picture_1 = QtWidgets.QToolButton(self.Item_GL_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Picture_1.sizePolicy().hasHeightForWidth())
        self.Picture_1.setSizePolicy(sizePolicy)
        self.Picture_1.setMinimumSize(QtCore.QSize(800, 150))
        self.Picture_1.setMaximumSize(QtCore.QSize(1000, 150))
        self.Picture_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Picture_1.setAutoFillBackground(False)
        self.Picture_1.setStyleSheet("background-color:rgb(0,0,0,0);")
        self.Picture_1.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../Images/UserUploaded imgs/Product.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Picture_1.setIcon(icon8)
        self.Picture_1.setIconSize(QtCore.QSize(200, 200))
        self.Picture_1.setObjectName("Picture_1")
        self.gridLayout_3.addWidget(self.Picture_1, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.Item_GL_1, 0, QtCore.Qt.AlignHCenter)
        self.Item_GL_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.Item_GL_3.setMinimumSize(QtCore.QSize(900, 350))
        self.Item_GL_3.setMaximumSize(QtCore.QSize(1000, 350))
        self.Item_GL_3.setStyleSheet("background-color:White;")
        self.Item_GL_3.setObjectName("Item_GL_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.Item_GL_3)
        self.gridLayout_6.setContentsMargins(30, 30, 30, 30)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Description_3 = QtWidgets.QWidget(self.Item_GL_3)
        self.Description_3.setStyleSheet("background-color: rgb(243, 243, 243);\n"
"")
        self.Description_3.setObjectName("Description_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Description_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Name_3 = QtWidgets.QToolButton(self.Description_3)
        self.Name_3.setMinimumSize(QtCore.QSize(719, 0))
        self.Name_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Name_3.setStyleSheet("background-color:rgb(0,0,0,0);")
        self.Name_3.setObjectName("Name_3")
        self.verticalLayout_5.addWidget(self.Name_3, 0, QtCore.Qt.AlignHCenter)
        self.Rate_3 = QtWidgets.QToolButton(self.Description_3)
        self.Rate_3.setMinimumSize(QtCore.QSize(90, 0))
        self.Rate_3.setStyleSheet("background-color: rgb(0,0,0,0)")
        self.Rate_3.setIcon(icon7)
        self.Rate_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Rate_3.setObjectName("Rate_3")
        self.verticalLayout_5.addWidget(self.Rate_3, 0, QtCore.Qt.AlignHCenter)
        self.Amount_3 = QtWidgets.QLabel(self.Description_3)
        self.Amount_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Amount_3.setObjectName("Amount_3")
        self.verticalLayout_5.addWidget(self.Amount_3, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_6.addWidget(self.Description_3, 1, 1, 1, 1)
        self.Picture_3 = QtWidgets.QToolButton(self.Item_GL_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Picture_3.sizePolicy().hasHeightForWidth())
        self.Picture_3.setSizePolicy(sizePolicy)
        self.Picture_3.setMinimumSize(QtCore.QSize(800, 150))
        self.Picture_3.setMaximumSize(QtCore.QSize(1000, 150))
        self.Picture_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Picture_3.setAutoFillBackground(False)
        self.Picture_3.setStyleSheet("background-color:rgb(0,0,0,0);")
        self.Picture_3.setText("")
        self.Picture_3.setIcon(icon8)
        self.Picture_3.setIconSize(QtCore.QSize(200, 200))
        self.Picture_3.setObjectName("Picture_3")
        self.gridLayout_6.addWidget(self.Picture_3, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.Item_GL_3, 0, QtCore.Qt.AlignHCenter)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.Main_VL.addWidget(self.scrollArea)
        self.Main.addLayout(self.Main_VL, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.Main)

        self.retranslateUi(Main_Customer)
        QtCore.QMetaObject.connectSlotsByName(Main_Customer)

    def retranslateUi(self, Main_Customer):
        _translate = QtCore.QCoreApplication.translate
        Main_Customer.setWindowTitle(_translate("Main_Customer", "Form"))
        self.Wishlist_PB_2.setText(_translate("Main_Customer", "نظرات"))
        self.ID_LB_2.setText(_translate("Main_Customer", "آیدی :"))
        self.ID_var_2.setText(_translate("Main_Customer", "ID"))
        self.Email_var_2.setText(_translate("Main_Customer", "Email"))
        self.Email_LB_2.setText(_translate("Main_Customer", "ایمیل :"))
        self.Name_var_2.setText(_translate("Main_Customer", "Name"))
        self.Name_LB_2.setText(_translate("Main_Customer", "نام : "))
        self.label_4.setText(_translate("Main_Customer", "Rate"))
        self.label_5.setText(_translate("Main_Customer", "رضایت :"))
        self.Unit_LB_2.setText(_translate("Main_Customer", "ریال"))
        self.Money_var_2.setText(_translate("Main_Customer", "<html><head/><body><p><span style=\" font-size:10pt;\">Money</span></p></body></html>"))
        self.Bal_LB_2.setText(_translate("Main_Customer", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">: موجودی</span></p></body></html>"))
        self.Shop_Name_LB_2.setText(_translate("Main_Customer", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">فروشگاه من</span></p></body></html>"))
        self.toolButton_4.setText(_translate("Main_Customer", "محصولات\n"
""))
        self.toolButton_3.setText(_translate("Main_Customer", "محصولات\n"
"من"))
        self.toolButton.setText(_translate("Main_Customer", "اضافه کردن\n"
" محصول"))
        self.toolButton_2.setText(_translate("Main_Customer", "اضافه کردن محصول"))
        self.label_3.setText(_translate("Main_Customer", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">: تصویر</span></p></body></html>"))
        self.label.setText(_translate("Main_Customer", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">: نام محصول</span></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("Main_Customer", "نام محصول را وارد کنید."))
        self.lineEdit_2.setPlaceholderText(_translate("Main_Customer", "توضیحات محصول را وارد کنید."))
        self.label_2.setText(_translate("Main_Customer", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">: توضیحات</span></p></body></html>"))
        self.Name.setText(_translate("Main_Customer", "Name"))
        self.Rate.setText(_translate("Main_Customer", "Rate / 5"))
        self.Amount.setText(_translate("Main_Customer", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">ریال</span><span style=\" font-size:12pt; font-weight:600;\"> Amount</span></p></body></html>"))
        self.Name_3.setText(_translate("Main_Customer", "Name"))
        self.Rate_3.setText(_translate("Main_Customer", "Rate / 5"))
        self.Amount_3.setText(_translate("Main_Customer", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">ریال</span><span style=\" font-size:12pt; font-weight:600;\"> Amount</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main_Customer = QtWidgets.QWidget()
    ui = Ui_Main_Customer()
    ui.setupUi(Main_Customer)
    Main_Customer.show()
    sys.exit(app.exec_())

